project_id = "irnwduyioawqwcxlesos"

[functions]
  [functions.admin-data]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.check-stripe-status]
    verify_jwt = false
  [functions.contract-engine]
    verify_jwt = false
  [functions.create-payout]
    verify_jwt = false
  [functions.create-promotion-checkout]
    verify_jwt = false
  [functions.create-stripe-account]
    verify_jwt = false
  [functions.pay-partner-commission]
    verify_jwt = false
  [functions.process-producer-payout]
    verify_jwt = false
  [functions.producer-data]
    verify_jwt = false
  [functions.scrape-stats]
    verify_jwt = false
  [functions.send-email]
    verify_jwt = false
  [functions.stripe-webhook]
    verify_jwt = false
  [functions.sync-to-drive]
    verify_jwt = false
  [functions.elevenlabs-music]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
